### ISSUE TITLE
Retry Fancy IMU (again)

### ISSUE THREAD

**Issue by amparks100** [FRC2714/2019Competition#94]
https://www.chiefdelphi.com/t/important-updates-involving-the-functionality-and-legality-of-analog-devices-imus-and-gyro-boards/348287

**Comment by amparks100** [comment]
Checksum invalid error

**Comment by amparks100** [comment]
https://www.chiefdelphi.com/t/adis16470-not-working-while-adis16448-does/346427/27

**Comment by GaganBhat** [comment]
NavX suffices.
